# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:      
      - image: circleci/golang:1.13
    steps:
      - checkout      
      - run:
          working_directory: /home/circleci/project/src/
          command: go mod download
      - run:
          working_directory: /home/circleci/project/src/osvtile
          command: go test -v ./...
      - run:
          working_directory: /home/circleci/project/src/osvtile/cmd/osvtiled
          command: go build
